# Generated by Django 5.2.5 on 2025-09-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
